apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchainapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchainapi
  template:
    metadata:
      labels:
        app: blockchainapi
    spec:
      containers:
      - name: blockchainapi
        image: mycaredev.azurecr.io/mycareblockchainapisep:__image_tag__
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: 250m
            memory: 1Gi
        ports:
        - containerPort: 4000
      imagePullSecrets:
        - name: regcred1
---
apiVersion: v1
kind: Service
metadata:
  name: blockchainapi
spec:
  type: LoadBalancer
  ports:
  - port: 4000
  selector:
    app: blockchainapi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels: 
    app: blockchainapi
  name: blockchainapi
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: blockchainapi
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50