trigger:
- release
stages:
- stage: PRODBuildAndTest
  displayName: 'Build and Test pipeline PROD'
  jobs: 
    - job: 'Build'
      displayName: 'Build job PROD'
      pool: 
        name: 'MyCare-Build'
      variables:
        - group: Mycare-KV-PROD
        - group: BlockChainAPI-BuildandValidation-PROD
        - group: Mycare-KV-PROD-Values #this VG has all the secrets parameterized to the kV values similar to MycareAPI. All the values are already on the KV, so just added all the values to the Mycare-KV-Dev and this variable group will be used in the diff environments.

      steps:
          - task: Bash@3
            displayName: 'Install truffle'
            inputs:
              targetType: 'inline'
              script: |
                npm uninstall truffle
                npm install truffle@5.0.5
          - task: NodeTool@0
            inputs:
              versionSpec: '8.x'
            displayName: 'Install Node.js'
          - task: Npm@1
            displayName: 'Install NPM Dependencies'
            inputs:
              verbose: true

          - task: Bash@3
            displayName: 'Set Base Directory'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                set -v
                CD=`pwd`
                echo ##vso[task.setvariable variable=MyCare.BaseDir;]${CD}

          - task: Bash@3
            displayName: 'Add keyvault.json for PROD environment'
            inputs:
              targetType: 'inline'
              script: |
                set -x
                cd $(System.DefaultWorkingDirectory)/
                FILE=keyvault.json
                touch $FILE
                cat > $FILE <<- EOM
                {
                  "RESOURCE_GROUP": "$(RESOURCEGROUP)",
                  "VAULT_NAME": "$(VAULTNAME)",
                  "APP_NAME": "$(APPNAME)",
                  "CLIENT_ID": "$(CLIENTID)",
                  "CLIENT_SECRET": "$(CLIENTSECRET)",
                  "KEY_VAULT_NAME": "$(KEYVAULTNAME)",
                  "VAULT_URI": "$(VAULTURI)",
                  "SECRET_NAME": "$(SECRETNAME)"
                }
                EOM                  

          - task: Bash@3
            displayName: 'Add API PORT'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                set -v
                echo PORT=$(ApiPort) >>profiles/prod.env

          - task: Bash@3
            displayName: 'Update Truffle Config'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                set -v
                sed -i "s/8540/$(EthereumPort)/" truffle-config.js

          - task: Bash@3
            displayName: 'Replace BASEDIR'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                set -v
                export BASEDIR=`pwd | sed -i 's/\//\\\//'`
                sed -i "s/^BASEDIR=.*$/^WEB3_HTTP='http:\/\/127.0.0.1:${BASEDIR}'/g" profiles/prod.env
                                      
          - task: Bash@3
            displayName: 'Deploy Contracts'
            inputs:
              targetType: 'inline'
              script: |
                #set -v
                #####
                # Import VSTS Variables
                export BASEDIR=$(BASEDIR)
                #
                #####
                cd ${BASEDIR}
                npm run deploy:contracts:prod

          - task: Bash@3
            displayName: 'Test Contracts'
            inputs:
              targetType: 'inline'
              script: |
                #set -v
                #####
                # Import VSTS Variables
                export BASEDIR=$(BASEDIR)
                #
                #####
                cd ${BASEDIR}
                npm run test:contracts:prod

          - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
            displayName: 'Prepare analysis on SonarCloud'
            inputs:
              SonarCloud: mynewSonarNW19
              organization: $(sonarorg)
              scannerMode: CLI
              configMode: manual
              cliProjectKey: $(sonarclikey)
              cliProjectName: $(sonarprojectname)
              cliSources: api
              extraProperties: |
                sonar.exclusions=bower_components/**/*, node_modules/**/*, **/*test*/**, migrations/*, api/models/*
                sonar.javascript.lcov.reportPaths=coverage/lcov.info

          - task: Bash@3
            displayName: 'Run API Tests'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                #set -v
                export BASEDIR=`pwd`
                echo BASEDIR=${BASEDIR}
                npm run test:api

          - task: Bash@3
            displayName: 'Run Junit'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                #set -v
                PORT=$(DbPort)
                export BASEDIR=`pwd`
                echo DB_PORT=`grep DB_PORT profiles/prod.env`
                echo BASEDIR=${BASEDIR} DB_PORT=${PORT}
                npm run test:junit

          - task: Bash@3
            displayName: 'Run LCOV'
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                #set -v
                PORT=$(DbPort)
                export BASEDIR=`pwd`
                echo DB_PORT=`grep DB_PORT profiles/prod.env`
                echo BASEDIR=${BASEDIR} DB_PORT=${PORT}
                npm run coverage
          - task: PublishTestResults@2
            displayName: 'Publish Test Results **/test-*.xml'
            inputs:
              testResultsFiles: '**/test-*.xml'      
          - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
            displayName: 'Run Code Analysis'

          - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
            displayName: 'Publish Quality Gate Result'
            inputs:
              pollingTimeoutSec: 3000  
          - task: Bash@3
            displayName: 'Create Artifact'
            inputs:
              targetType: 'inline'
              script: |
                tar zcvf /tmp/BlockchainAPI.gzip .
                mv /tmp/BlockchainAPI.gzip .

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
            inputs:
              PathtoPublish: BlockchainAPI.gzip      
          - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
            displayName: 'Clean Agent Directories copy'    
 #######################  build container PROD  #################################                     
- stage: 'PRODBuild'
  displayName: 'Build container PROD'
  dependsOn: PRODBuildAndTest
  jobs: 
    - job: 'Build'
      displayName: 'Docker Image PROD'
      pool: 
        vmImage: 'ubuntu-latest'
      variables:
        - group: Mycare-KV-PROD
        - group: BlockChainAPI-BuildandValidation-PROD
        - group: Mycare-KV-PROD-Values #this VG has all the secrets parameterized to the kV values similar to MycareAPI. All the values are already on the KV, so just added all the values to the Mycare-KV-Dev and this variable group will be used in the diff environments.
      steps:
          - task: DockerInstaller@0
            displayName: 'Install Docker 17.09.0-ce'
          - task: Bash@3
            displayName: 'Inject keyvault details'
            inputs:
              targetType: 'inline'
              script: |
                set -x
                          FILE=keyvault.json
                          echo $(RESOURCEGROUP)
                          touch $FILE
                          cat > $FILE <<- EOM
                          {
                              "RESOURCE_GROUP": "$(RESOURCEGROUP)",
                              "VAULT_NAME": "$(VAULTNAME)",
                              "APP_NAME": "$(APPNAME)",
                              "CLIENT_ID": "$(CLIENTID)",
                              "CLIENT_SECRET": "$(CLIENTSECRET)",
                              "KEY_VAULT_NAME": "$(KEYVAULTNAME)",
                              "VAULT_URI": "$(VAULTURI)",
                              "SECRET_NAME": "$(SECRETNAME)"
                          }
                EOM
              workingDirectory: '$(System.DefaultWorkingDirectory)'

          - task: Bash@3
            displayName: 'cat keyvault.json file from System.DefaultWorkingDirectory'
            inputs:
              targetType: 'inline'
              script: |
                          cat $(System.DefaultWorkingDirectory)/keyvault.json
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in Dockerfile'
            inputs:
              targetFiles: Dockerfile
              tokenPrefix: '__'
              tokenSuffix: '__'

          - task: Docker@2
            displayName: buildAndPush
            inputs:
              containerRegistry: mycareacr  #acr service connection
              repository: $(acrrepo)
              Dockerfile: Dockerfile
              buildContext: .
              tags: 'BlockchainApi-$(MYENV)-$(Build.BuildNumber)'

          - task: Bash@3
            displayName: echo Docker Image tag
            inputs:
              targetType: 'inline'
              script: 'echo "Docker image ready for deployment is Blockchainapi-$(MYENV)-$(Build.BuildNumber)"'

#####################  DEPLOYMENT  To PROD AKS  #####################

- stage: 'PRODDeploy'
  displayName: 'Deploy to PROD AKS'
  dependsOn: PRODBuild
  jobs: 
    - deployment: deployaksprod
      environment: PROD
      displayName: 'Deploy Job PROD'
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        - name: image_tag
          value: 'BlockchainApi-$(MYENV)-$(Build.BuildNumber)'
        - group: Mycare-KV-PROD
        - group: BlockChainAPI-BuildandValidation-PROD
        - group: Mycare-KV-PROD-Values #this VG has all the secrets parameterized to the kV values similar to MycareAPI. All the values are already on the KV, so just added all the values to the Mycare-KV-Dev and this variable group will be used in the diff environments.
      strategy:
       runOnce:
          deploy:
            steps:
                - checkout: self
                - download: none
                - task: qetza.replacetokens.replacetokens-task.replacetokens@3
                  displayName: 'Replace tokens in Deployment.yml'
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)'
                    targetFiles: Deployment.yml
                    escapeType: none
                    verbosity: detailed
                    tokenPrefix: '__'
                    tokenSuffix: '__'

                - task: Kubernetes@1
                  displayName: 'kubectl apply'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'MyCare-EastUS-PROD-AKS-APP'
                    command: 'apply'
                    useConfigurationFile: true
                    configuration: '$(Build.SourcesDirectory)/Deployment.yml'