module.exports = [
    'RPC_ENDPOINT',
    'ACCOUNT_ADDRESS',
    'ACCOUNT_PRIVATE_KEY',
    'NETWORK_ID',
    'ADMIN_EMAIL',
    'ADMIN_PASSWORD',
    'EMAIL_HOST',
    'EMAIL_USER',
    'EMAIL_PASS',
    'JWT_TOKEN',
    'MONGODB_URI',
    'AZURE_STORAGE_CONNECTION_STRING',
    'AZURE_STORAGE_QUEUE_NAME',
    'APP_LOGS_BLOB_CONTAINER'
];
